Introduce MBMenuSurface
Material-Blazor/Material.Blazor pull request #420
Opened 2021-03-10 14:44 UTC by HannahKiekens

Intended UseCase:

``` razor
    <MBIconButton @onclick="@OpenMenuSurfaceAsync" Icon="account_circle" />
    <div class="mdc-menu-surface--anchor">
        <MBMenuSurface @ref="MenuSurface" >
            <div>
                <div style="height:100px; width:100px; background-size: contain; background-image: url('_content/Material.Blazor.Website/icon-512.png');"></div>
                <div class="mdc-typography mdc-typography--headline6">
                            Hannah Kiekens
                </div>
                <div class="mdc-typography mdc-typography--subtitle1">
                            hannahkiekens@gmail.com
                </div>
            </div>
            <MBIconButton Icon="logout"/>
            <MBIconButton Icon="settings"/>
        </MBMenuSurface>
    </div>
@code {
    private MBMenuSurface MenuSurface { get; set; }

    private async Task OpenMenuSurfaceAsync()
    {
        await MenuSurface.ToggleAsync();
    }
}
```

2021-03-10 14:47 UTC, HannahKiekens commented
Ok, what I really needed was an MBMenuSurface type component

I am looking for some feedback, if this looks good, I'll finish documentation for this Component

2021-03-10 16:22 UTC, MarkStega commented
Hannah,

On first review this looks good. It would definitely be a 'plus' component since Material doesn't define such a component.
I have a couple of questions:

1) What makes it desirable to make this a component of Material.Blazor as opposed to a component in your application? I may be missing something but I didn't see anything in the implementation that made it 'better' by being part of M.B

2) Before documenting could you add at least a minimal demo page in Material.Blazor.Website? Just implementing your example from the beginning of this PR should be sufficient.

I am going to ask Simon to take a look at this PR also...

2021-03-10 17:09 UTC, simonziegler commented
Hey @HannahKiekens, thanks for contributing this. @MarkStega and I just had a conversation and decided that I will be reviewing your PR. I have quite a lot of work on right now so anticipate getting there in perhaps a couple of weeks.

Simon

2021-03-10 17:58 UTC, HannahKiekens commented
@MarkStega 
Having this Component in Material.Blazor would be a great extension point for custom Picker components & freeform menus, like the demo code. 
My first attempt involved modifying ComponentFoundation #419 so I could inherit from it in my own project. That did not seem like the correct solution.

2021-03-10 18:12 UTC, HannahKiekens commented
@simonziegler 
Thx, I'll make sure to get this pull request up to standards. 


I am working on a major CMS/Dashboard rewrite. Improving extension points like this just seem best to do upstream.
Material.Blazor has been easy to work with and understand for my team.

2021-03-10 18:13 UTC, simonziegler commented
That's great to hear, and I'd love to know more.

2021-03-15 15:53 UTC, MarkStega commented
1) The demo page is looking good, but I am surprised to see a vertical scroll bar on the surface. Is that intentional?
2) I would think that on selection of either of the two menu items that the surface should close & you should follow the 'convention of 'menu.razor' and do the toast showing the selection. Do you agree?

With those two comments addressed and a documentation page I think this should be good to go.

2021-03-16 09:13 UTC, HannahKiekens commented
This build-documentation failure doesnt seem related to what I did?

Critical failure uploading 'D:\a\Material.Blazor\Material.Blazor\siteDocFx\api\Material.Blazor.MBSlidingContent-1.html'

2021-03-16 09:49 UTC, stefanloerwald commented
> This build-documentation failure doesnt seem related to what I did?
> 
> Critical failure uploading 'D:\a\Material.Blazor\Material.Blazor\siteDocFx\api\Material.Blazor.MBSlidingContent-1.html'

It really doesn't. This is my fault and I'll fix asap.

2021-03-16 13:06 UTC, MarkStega commented
Hannah,

It's looking good; I gave you a two part question which was bad form (#2 above). You addressed the toast so hear is what should have been a separate question:

3) I would think that on selection of either of the two menu items that the surface should close. Do you agree? If not, what is the workflow that you envision for the surface?

2021-03-16 13:41 UTC, HannahKiekens commented
> 1. I would think that on selection of either of the two menu items that the surface should close. Do you agree? If not, what is the workflow that you envision for the surface?

I intended this to be a dumb wrapper for @material/menu-surface.
The typescript API is ever so slightly different than a full menu

There are 2 usecases:

1. Freeform menus, like the example, wich is intended to wrap a C# ClaimsPrincipal. 
2. Custom Pickers, like ColorPicker ...

I believe there should not be any added intelligence here. This Component is intended to be used in other more complex Components, written in pure C#

2021-03-16 13:58 UTC, MarkStega commented
Perhaps the best 'solution' then is to expand the demo a very small amount to show the surface in a more complete use case or two...

2021-03-26 11:30 UTC, simonziegler commented
@HannahKiekens we just merged a fairly substantial PR of mine and next are going to merge one from @stefanloerwald in the coming few days. These will both change things a little for your code. First `DestroyMcwComponent` has gone, and second Stefan has changed attribute splatting quite dramatically. Hopefully the changes you will need to make are moderate. I suggest waiting for Stefan's PR to be merged before you update your code.

2021-03-26 11:57 UTC, stefanloerwald commented
I'm going to perform a few more changes, but first will have some lunch. In the mean time we'll probably see a few broken builds, but that's fine.

2021-03-26 12:39 UTC, stefanloerwald commented on Material.Blazor/Components/MenuSurface/MBMenuSurface.razor
> +     @attributes="@AttributesToSplat()">
To be replaced by 
```
class="mdc-menu-surface mdc-menu-surface--fixed @ActiveConditionalClasses @(@class)"
style="@style"
id="@id"
@attributes="@AttributesToSplat()"
```
when #421 is merged.

2021-03-26 12:40 UTC, stefanloerwald commented on Material.Blazor/Components/MenuSurface/MBMenuSurface.razor.cs
> +            ClassMapperInstance
To be replaced with `ConditionalCssClasses` when #421 is merged.

2021-03-26 12:40 UTC, stefanloerwald commented on Material.Blazor/Components/MenuSurface/MBMenuSurface.razor.cs
> +                .Add("mdc-menu-surface mdc-menu-surface--fixed")
To be removed when #421 is merged.

2021-03-26 12:42 UTC, stefanloerwald commented on Material.Blazor/Components/MenuSurface/MBMenuSurface.razor.cs
> +        }
Consider replacing with
```cs
[JSInvokable]
public void NotifyClosed()
{
   IsOpen = false;
}
```
I don't see a reason this call needs to be async at all. I also don't think the argument to JSInvokable is necessary unless the method name differs.

2021-03-26 12:43 UTC, stefanloerwald commented on Material.Blazor/Components/MenuSurface/MBMenuSurface.razor
> +     @attributes="@AttributesToSplat()">
Actually, `mdc-menu-surface--fixed` looks like it should be conditional.

2021-03-26 12:46 UTC, stefanloerwald commented on Material.Blazor/Components/MenuSurface/MBMenuSurface.razor
> +     @attributes="@AttributesToSplat()">
@HannahKiekens, please review whether `mdc-menu-surface--fixed` should be applied unconditionally or conditionally and just leave a comment here. I'll then adjust the code together with the changes necessary after #421 in one go.

2021-03-26 13:15 UTC, stefanloerwald commented on Material.Blazor/Components/MenuSurface/MBMenuSurface.razor.cs
> +        internal static string GetMenuSurfacePositioningClass(MBMenuSurfacePositioning surfacePositioning) =>
Consider declaring this private. I can't see why this is necessary outside this component.

2021-03-26 19:31 UTC, simonziegler commented
@HannahKiekens, we managed to get through what we needed to deal with so that we can now consider your PR. You'll notice that @stefanloerwald has updated your code a bit to catch up with the conflicts created by what we've been doing. Can you please have a look at what @MarkStega suggested about the website demo page and let us know when you feel ready for us to review the PR again? If you can manage this within the next few days we'll look to include this in the upcoming preview4.

2021-04-03 12:28 UTC, simonziegler requested changes
I'm fully happy with this PR except for the need to respond to @stefanloerwald's comments.

2021-04-03 13:49 UTC, stefanloerwald commented
I just performed those minor changes myself, which also makes it consistent with the rest of the code base. Fine to merge from my side

2021-04-03 13:55 UTC, merged